Add scripts for crawling data from the official API of Steam (issue #5)
BrakeValve/dataflow pull request #13
Opened 2016-10-28 16:43 UTC by SLMT

There are 3 scripts and 1 additional file.

- `steam-api-cralwer.py` crawls the metadata and the price data of apps. The list of the apps are retrieved from an official API. The list consists of all the apps can be found on Steam.
- `generate_ignore_list.py` generates an `ingores_app.txt` list consists of apps that in the app list mentioned above, but cannot be accessed from API. `steam-api-cralwer.py` will ignore the apps listed in `ingores_app.txt`. I have already generated one in the commits.

For more information about how to use these scripts, please apply `-h` flag on them.

2016-10-31 06:12 UTC, cyhsutw requested changes

2016-10-31 06:12 UTC, cyhsutw commented on data-crawler/steam-api/util.py
> +WAITTING_TIME = 10  # in seconds
```diff
- WAITTING_TIME = 10
+ WAITING_TIME = 10
```

2016-10-31 06:13 UTC, cyhsutw commented
Thanks, @SLMT. I think it's good to 🚢  after fixing that minor typo.

2016-11-01 11:58 UTC, cyhsutw approved these changes

2016-11-07 04:44 UTC, merged

2016-11-10 02:10 UTC, SLMT commented
Thanks @cyhsutw for fixing the typo